# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('timestamp_start', models.DateTimeField()),
                ('timestamp_end', models.DateTimeField()),
                ('shared', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CalendarNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calendar_name', models.CharField(max_length=100)),
                ('timestamp_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CalendarNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_text', models.TextField()),
                ('timestamp_created', models.DateTimeField()),
                ('shared', models.BooleanField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.Calendar')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='calendarnotes',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.Users'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='calendarnames',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.CalendarNames'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.Users'),
        ),
    ]
